# Generated by Django 5.0.3 on 2024-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='profiles/'),
        ),
    ]
