# Generated by Django 5.0.3 on 2024-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('location', models.TextField(max_length=30)),
                ('ingredians', models.TextField(max_length=50)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
