# Generated by Django 5.0.3 on 2024-03-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_products_image_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Food',
        ),
    ]
