# Generated by Django 5.0.3 on 2024-03-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_products_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
